// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace IglesiaGPS.Api.Migrations
{
    [DbContext(typeof(IglesiaGPSApiContext))]
    partial class IglesiaGPSApiContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("IglesiaGPS.modelo.Cancion", b =>
                {
                    b.Property<int>("CancionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CancionId"));

                    b.Property<string>("Autor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("CreadoPorUsuarioId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Letra")
                        .HasColumnType("text");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Tono")
                        .HasColumnType("text");

                    b.Property<string>("UrlAudio")
                        .HasColumnType("text");

                    b.HasKey("CancionId");

                    b.HasIndex("CreadoPorUsuarioId");

                    b.ToTable("Canciones");
                });

            modelBuilder.Entity("IglesiaGPS.modelo.ListaCancionDetalle", b =>
                {
                    b.Property<int>("ListaCancionDetalleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ListaCancionDetalleId"));

                    b.Property<int>("CancionId")
                        .HasColumnType("integer");

                    b.Property<int>("ListaCancionesId")
                        .HasColumnType("integer");

                    b.Property<int>("Orden")
                        .HasColumnType("integer");

                    b.HasKey("ListaCancionDetalleId");

                    b.HasIndex("CancionId");

                    b.HasIndex("ListaCancionesId");

                    b.ToTable("ListaCancionDetalles");
                });

            modelBuilder.Entity("IglesiaGPS.modelo.ListaCanciones", b =>
                {
                    b.Property<int>("ListaCancionesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ListaCancionesId"));

                    b.Property<int>("DirectorId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaPublicacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Publicada")
                        .HasColumnType("boolean");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ListaCancionesId");

                    b.HasIndex("DirectorId");

                    b.ToTable("ListaCanciones");
                });

            modelBuilder.Entity("IglesiaGPS.modelo.NotaMusical", b =>
                {
                    b.Property<int>("NotaMusicalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("NotaMusicalId"));

                    b.Property<int>("CancionId")
                        .HasColumnType("integer");

                    b.Property<string>("Contenido")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("EditadoPorUsuarioId")
                        .HasColumnType("integer");

                    b.Property<string>("Instrumento")
                        .HasColumnType("text");

                    b.Property<DateTime>("UltimaEdicion")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("NotaMusicalId");

                    b.HasIndex("CancionId");

                    b.HasIndex("EditadoPorUsuarioId");

                    b.ToTable("NotaMusicales");
                });

            modelBuilder.Entity("IglesiaGPS.modelo.Recomendacion", b =>
                {
                    b.Property<int>("RecomendacionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RecomendacionId"));

                    b.Property<int>("CancionId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaRecomendacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Leida")
                        .HasColumnType("boolean");

                    b.Property<string>("Mensaje")
                        .HasColumnType("text");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("RecomendacionId");

                    b.HasIndex("CancionId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Recomendaciones");
                });

            modelBuilder.Entity("IglesiaGPS.modelo.RegistroActividad", b =>
                {
                    b.Property<int>("RegistroActividadId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RegistroActividadId"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EntidadAfectada")
                        .HasColumnType("text");

                    b.Property<int?>("EntidadId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaAccion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TipoAccion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("RegistroActividadId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("RegistroActividad");
                });

            modelBuilder.Entity("IglesiaGPS.modelo.Rol", b =>
                {
                    b.Property<int>("RolId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RolId"));

                    b.Property<string>("CodigoAcceso")
                        .HasColumnType("text");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("RolId");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("IglesiaGPS.modelo.SolicitudDirector", b =>
                {
                    b.Property<int>("SolicitudDirectorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SolicitudDirectorId"));

                    b.Property<string>("CodigoIngresado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("FechaRespuesta")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaSolicitud")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("RespuestaPorUsuarioId")
                        .HasColumnType("integer");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("SolicitudDirectorId");

                    b.HasIndex("RespuestaPorUsuarioId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("SolicitudDirectores");
                });

            modelBuilder.Entity("IglesiaGPS.modelo.Usuario", b =>
                {
                    b.Property<int>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UsuarioId"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Contrasena")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("PuedeEditarNotas")
                        .HasColumnType("boolean");

                    b.Property<int>("RolId")
                        .HasColumnType("integer");

                    b.HasKey("UsuarioId");

                    b.HasIndex("RolId");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("IglesiaGPS.modelo.Cancion", b =>
                {
                    b.HasOne("IglesiaGPS.modelo.Usuario", "CreadoPor")
                        .WithMany()
                        .HasForeignKey("CreadoPorUsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreadoPor");
                });

            modelBuilder.Entity("IglesiaGPS.modelo.ListaCancionDetalle", b =>
                {
                    b.HasOne("IglesiaGPS.modelo.Cancion", "Cancion")
                        .WithMany("ListaCancionDetalles")
                        .HasForeignKey("CancionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IglesiaGPS.modelo.ListaCanciones", "ListaCanciones")
                        .WithMany("Detalles")
                        .HasForeignKey("ListaCancionesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cancion");

                    b.Navigation("ListaCanciones");
                });

            modelBuilder.Entity("IglesiaGPS.modelo.ListaCanciones", b =>
                {
                    b.HasOne("IglesiaGPS.modelo.Usuario", "Director")
                        .WithMany("ListasCanciones")
                        .HasForeignKey("DirectorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Director");
                });

            modelBuilder.Entity("IglesiaGPS.modelo.NotaMusical", b =>
                {
                    b.HasOne("IglesiaGPS.modelo.Cancion", "Cancion")
                        .WithMany("NotasMusicales")
                        .HasForeignKey("CancionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IglesiaGPS.modelo.Usuario", "EditadoPor")
                        .WithMany()
                        .HasForeignKey("EditadoPorUsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cancion");

                    b.Navigation("EditadoPor");
                });

            modelBuilder.Entity("IglesiaGPS.modelo.Recomendacion", b =>
                {
                    b.HasOne("IglesiaGPS.modelo.Cancion", "Cancion")
                        .WithMany("Recomendaciones")
                        .HasForeignKey("CancionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IglesiaGPS.modelo.Usuario", "Usuario")
                        .WithMany("Recomendaciones")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cancion");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("IglesiaGPS.modelo.RegistroActividad", b =>
                {
                    b.HasOne("IglesiaGPS.modelo.Usuario", "Usuario")
                        .WithMany("Actividades")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("IglesiaGPS.modelo.SolicitudDirector", b =>
                {
                    b.HasOne("IglesiaGPS.modelo.Usuario", "RespuestaPor")
                        .WithMany("SolicitudesRespondidas")
                        .HasForeignKey("RespuestaPorUsuarioId");

                    b.HasOne("IglesiaGPS.modelo.Usuario", "Usuario")
                        .WithMany("Solicitudes")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RespuestaPor");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("IglesiaGPS.modelo.Usuario", b =>
                {
                    b.HasOne("IglesiaGPS.modelo.Rol", "Rol")
                        .WithMany("Usuarios")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("IglesiaGPS.modelo.Cancion", b =>
                {
                    b.Navigation("ListaCancionDetalles");

                    b.Navigation("NotasMusicales");

                    b.Navigation("Recomendaciones");
                });

            modelBuilder.Entity("IglesiaGPS.modelo.ListaCanciones", b =>
                {
                    b.Navigation("Detalles");
                });

            modelBuilder.Entity("IglesiaGPS.modelo.Rol", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("IglesiaGPS.modelo.Usuario", b =>
                {
                    b.Navigation("Actividades");

                    b.Navigation("ListasCanciones");

                    b.Navigation("Recomendaciones");

                    b.Navigation("Solicitudes");

                    b.Navigation("SolicitudesRespondidas");
                });
#pragma warning restore 612, 618
        }
    }
}
